import Head from "next/head";
import Navbar from "@/components/navbar/navbar";
import HeroArea from "@/components/hero-area/hero-area";
import OurStory from "@/components/our-story/our-story";
import Menu from "@/components/menu-area/menu";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link
          href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@300;400;500;700;900&family=Roboto:wght@300;400;500;700;900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HeroArea />
      <OurStory />
      <Menu />
    </>
  );
}
